### ISSUE TITLE
chore(web) - migrate to tailwind

### ISSUE THREAD

**Issue by fullstackslayer** [hydralite/hydralite#103]
fuck.

**Comment by samarmohan** [comment]
yes.

**Comment by fullstackslayer** [comment]
yes.

**Comment by samarmohan** [comment]
I'll create a PR getting set up with Tailwind.

**Comment by fullstackslayer** [comment]
we already finished the migration lol. we just need to fix a small thing and merge the branch into dev

**Comment by ZaphodElevated** [comment]
There are still a few components which are using sass

I'm fixing it and creating a pr
