### ISSUE TITLE
feat(api): enhance project entity

### ISSUE THREAD

**Issue by fullstackslayer** [hydralite/hydralite#11]
TASK -> Add project comments
  TASK -> Add project groups
  TASK --> Add project announcements
  TASK --> Add project posts
  TASK -> Add project scheduled meeting rooms
  TASK -> Add project tasks
  TASK -> Add project feature board
  TASK -> Add project reporting
  TASK -> Add project marketing credits

(api\src\db\entity\Project.entity.ts)

**Comment by fullstackslayer** [comment]
waitlisted due to https://github.com/hydralite/hydralite/issues/32

**Comment by VarunPotti** [comment]
Messages schema for the schema "Project", wherein other users can give feedback and/or ideas
