### ISSUE TITLE
feat(web) - Add a code editor 

### ISSUE THREAD

**Issue by Zynx64** [hydralite/hydralite#48]
### feat(web) - Add a code editor
Along with syntax highlighting for the respective language for each projects,
Whether it be python, typescript, javascript, Java or lua, etc...
editor example : [**Github Gist**] https://gist.github.com/

**Comment by fullstackslayer** [comment]
Where would this have implications in a project. Would it be in the source control tab if they link github/gitlab/bitbucket to the project? Would it be in a project post?

**Comment by Zynx64** [comment]
> Where would this have implications in a project. Would it be in the source control tab if they link github/gitlab/bitbucket to the project? Would it be in a project post?

Basically github repos contaion code right ? while pushing and making changes to a repo's or a potential project's code,
isn't there a code editor ? not a fully fledged IDE, but ye.

**Comment by VarunPotti** [comment]
https://theia-ide.org/ This seems something to be considered

**Comment by Zynx64** [comment]
> https://theia-ide.org/ This seems something to be considered. I mean it is opensource https://github.com/eclipse-theia/theia so it should be free

If we use something like that, it'll become an IDE

**Comment by Zynx64** [comment]
but ye, we can use eclipse theia

**Comment by fullstackslayer** [comment]
Lgtm, this will integrate into the project dashboard and will be visible if they have installed GitHub/gitlab/bitbucket as a third party app

**Comment by fullstackslayer** [comment]
Okay folks, theres an issue. Thiea isnt a collaborative ide, I've ruled out a few options/alternatives:

1. We ditch thiea and try finding a collaborative ide 
2. We propose some form of repl.it integration
3. We use https://togetherjs.com/ (This is the worst-case scenario, but even jsfiddle uses it)

Also, just using the live share extension on thiea is not legal, because ms live share is closed source and only meant to be used in Microsoft products.

**Comment by Zynx64** [comment]
> Okay folks, theres an issue. Thiea isnt a collaborative ide, I've ruled out a few options/alternatives:
> 
> 1. We ditch thiea and try finding a collaborative ide
> 2. We propose some form of repl.it integration
> 3. We use https://togetherjs.com/ (This is the worst-case scenario, but even jsfiddle uses it)
> 
> Also, just using the live share extension on thiea is not legal, because ms live share is closed source and only meant to be used in Microsoft products.

Lgtm ig

**Comment by Zynx64** [comment]
Actually many poor web IDE's use together.js lol

**Comment by fullstackslayer** [comment]
> Actually many poor web IDE's use together.js lol

lol true

**Comment by ShubhamPatilsd** [comment]
Microsoft's Monaco Editor would have been great for this but it is not collaborative :disappointed:
