### ISSUE TITLE
fix(web) - make landing page mobile responsive

### ISSUE THREAD

**Issue by fullstackslayer** [hydralite/hydralite#49]
make a branch for it btw - `fix/web/responsive`

**Comment by fullstackslayer** [comment]
whatever u merge for the landing page, make sure to directly merge it into prod and don't ever make a merge from the dev branch until we need to put something actual on production.

**Comment by ZaphodElevated** [comment]
Completed Mobile Repsonsiveness

Pull request - https://github.com/hydralite/hydralite/pull/53
