### ISSUE TITLE
fix(landing) - make responsive for the viewport in between mobile and laptop

### ISSUE THREAD

**Issue by fullstackslayer** [hydralite/hydralite#54]
if you clone the Dev branch and resize the window a bit, you will notice it's responsive   on mobile and laptop, but there's an ugly horizontal scroll bar in between the viewports. try and make that whole segment responsive.

**Comment by f1shy-dev** [comment]
working on this

**Comment by fullstackslayer** [comment]
closing due to creation of https://github.com/hydralite/hydralite/issues/65
