### ISSUE TITLE
chore(landing) - migrate from getwaitlist to firebase

### ISSUE THREAD

**Issue by fullstackslayer** [hydralite/hydralite#56]
in the pages/api/waitlist.ts file, remove the get waitlist API calls and add the email received in req.body to a firebase collection instead. We will iterate through this collection to send an email to each waitlisted user once the product is out.

**Comment by ZaphodElevated** [comment]
- Completed
- https://github.com/hydralite/hydralite/commit/0bbc7bcae064122a762b0c7675371d3351560149
