### ISSUE TITLE
fix(landing) - validation before inserting into firestore

### ISSUE THREAD

**Issue by fullstackslayer** [hydralite/hydralite#61]
add email regex validation and also make sure there aren't any duplicate emails before inserting an email into the firestore "waitlist" collection.

(landing\util\firestoreManager.ts, line 14)

**Comment by ZaphodElevated** [comment]
Done in https://github.com/hydralite/hydralite/commit/c899ce203a1768f1a912a5e56c82e1a6f3561e74
