### ISSUE TITLE
fix(landing) - screen responsiveness

### ISSUE THREAD

**Issue by ZaphodElevated** [hydralite/hydralite#65]
- Fix screen responsiveness of landing page
- Problems at width between 660 to 1250 pixels

**Comment by fullstackslayer** [comment]
assigned to @mooyg

**Comment by fullstackslayer** [comment]
assigned to @ShubhamPatilsd

**Comment by ShubhamPatilsd** [comment]
Hello I just made a pull request for this! :grin:
